using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEngine;

namespace TurnKit.Editor
{
    public static class EnumGenerator
    {
        private const string OutputPath = "Assets/TurnKit/Runtime/Generated/RelayListNames.cs";

        private static readonly HashSet<string> ReservedListNames = new()
        {
            "abstract","as","base","bool","break","byte","case","catch","char","checked","class","const",
            "continue","decimal","default","delegate","do","double","else","enum","event","explicit",
            "extern","false","finally","fixed","float","for","foreach","goto","if","implicit","in","int",
            "interface","internal","is","lock","long","namespace","new","null","object","operator","out",
            "override","params","private","protected","public","readonly","ref","return","sbyte","sealed",
            "short","sizeof","stackalloc","static","string","struct","switch","this","throw","true","try",
            "typeof","uint","ulong","unchecked","unsafe","ushort","using","virtual","void","volatile","while",
            "add","alias","ascending","async","await","by","descending","dynamic","equals","from","get",
            "global","group","init","into","join","let","managed","nameof","nint","not","notnull","nuint",
            "on","or","orderby","partial","record","remove","required","scoped","select","set","unmanaged",
            "value","var","when","where","with","yield", "spawn"
        };

        public static void Generate(TurnKitConfig config)
        {
            if (config == null || config.relayConfigs == null || config.relayConfigs.Count == 0)
            {
                Debug.LogWarning("[TurnKit] No relay configs to generate enums from");
                return;
            }

            if (!Validate(config))
                return;

            var generated = BuildGeneratedContent(config);

            string directory = Path.GetDirectoryName(OutputPath);
            if (!Directory.Exists(directory))
            {
                Directory.CreateDirectory(directory);
            }

            File.WriteAllText(OutputPath, generated);
            AssetDatabase.Refresh();

            Debug.Log($"[TurnKit] Generated relay config enums at {OutputPath}");
        }

        public static bool HasChanges(TurnKitConfig config)
        {
            if (config == null || config.relayConfigs == null || config.relayConfigs.Count == 0)
                return false;

            if (!File.Exists(OutputPath))
                return true;

            string existing = File.ReadAllText(OutputPath);
            string generated = BuildGeneratedContent(config);

            return existing != generated;
        }

        private static string BuildGeneratedContent(TurnKitConfig config)
        {
            var sb = new StringBuilder();
            var generatedClassNames = new List<(string Slug, string ClassName)>();

            sb.AppendLine("// This file is auto-generated by TurnKit. Do not edit manually.");
            sb.AppendLine("// Generated from relay configurations in TurnKitConfig");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine();
            sb.AppendLine("namespace TurnKit");
            sb.AppendLine("{");

            foreach (var relay in config.relayConfigs)
            {
                if (relay == null) continue;

                string className = ToConfigClassName(relay.slug);
                generatedClassNames.Add((relay.slug, className));

                sb.AppendLine($"    public static class {className}");
                sb.AppendLine("    {");
                sb.AppendLine($"        public const string Slug = \"{relay.slug}\";");

                if (relay.lists != null && relay.lists.Count > 0)
                {
                    // 1. Generate local Enums
                    // List Enum: Specific to this Relay
                    sb.AppendLine();
                    sb.AppendLine("        public enum List { " + string.Join(", ", relay.lists.Select(l => l.name)) + " }");

                    // Tag Enum: Gather all unique tags used in this specific Relay config
                    var uniqueTags = relay.lists
                        .Select(l => l.tag)
                        .Where(t => !string.IsNullOrEmpty(t))
                        .Distinct()
                        .ToList();

                    string tagMembers = uniqueTags.Count > 0 ? string.Join(", ", uniqueTags) : "";
                    sb.AppendLine($"        public enum Tag {{ {tagMembers} }}");

                    // 2. Generate the Metadata Dictionary
                    sb.AppendLine();
                    sb.AppendLine(
                        $"        public static readonly Dictionary<List, TurnKitConfig.RelayListConfig> Metadata = new()");
                    sb.AppendLine("        {");

                    foreach (var list in relay.lists)
                    {
                        string ownerSlots = string.Join(", ", list.ownerSlots.Select(s => $"TurnKitConfig.PlayerSlot.{s}"));
                        string visibleSlots = string.Join(", ", list.visibleToSlots.Select(s => $"TurnKitConfig.PlayerSlot.{s}"));
                        string tagEnumValue = $"Tag.{list.tag}";

                        sb.AppendLine($"            {{ List.{list.name}, new TurnKitConfig.RelayListConfig {{");
                        sb.AppendLine($"                name = \"{list.name}\",");
                        // Use nameof() so the string in the Metadata matches the Enum name perfectly
                        sb.AppendLine($"                tag = nameof({tagEnumValue}),");
                        sb.AppendLine($"                ownerSlots = new List<TurnKitConfig.PlayerSlot> {{ {ownerSlots} }},");
                        sb.AppendLine(
                            $"                visibleToSlots = new List<TurnKitConfig.PlayerSlot> {{ {visibleSlots} }}");
                        sb.AppendLine("            } },");
                    }

                    sb.AppendLine("        };");
                }

                sb.AppendLine("    }");
                sb.AppendLine();
            }

            // 3. Generate the Unified Registry
            sb.AppendLine("    public static class Registry");
            sb.AppendLine("    {");
            sb.AppendLine("        public static readonly Dictionary<string, Action> Initializers = new()");
            sb.AppendLine("        {");

            for (int i = 0; i < generatedClassNames.Count; i++)
            {
                var item = generatedClassNames[i];
                string comma = i < generatedClassNames.Count - 1 ? "," : "";
                // Note: InitializeFromMetadata needs to accept the Dictionary<List, RelayListConfig>
                sb.AppendLine(
                    $"            {{ \"{item.Slug}\", () => Relay.Instance.InitializeFromMetadata({item.ClassName}.Metadata) }}{comma}");
            }

            sb.AppendLine("        };");
            sb.AppendLine("    }");

            sb.AppendLine("}");
            return sb.ToString();
        }

        private static bool Validate(TurnKitConfig config)
        {
            var relaySlugs = new HashSet<string>();
            var relayClassNames = new HashSet<string>();

            foreach (var relay in config.relayConfigs)
            {
                if (relay == null)
                {
                    Debug.LogError("[TurnKit] Relay config contains a null entry.");
                    return false;
                }

                if (string.IsNullOrWhiteSpace(relay.slug))
                {
                    Debug.LogError("[TurnKit] Relay config slug cannot be empty.");
                    return false;
                }

                if (!relaySlugs.Add(relay.slug))
                {
                    Debug.LogError($"[TurnKit] Duplicate relay config slug '{relay.slug}'.");
                    return false;
                }

                string className = ToConfigClassName(relay.slug);
                if (!relayClassNames.Add(className))
                {
                    Debug.LogError($"[TurnKit] Relay config class name collision. Multiple slugs generate the same class '{className}'.");
                    return false;
                }

                if (relay.lists == null)
                    continue;

                var listNames = new HashSet<string>();
                foreach (var list in relay.lists)
                {
                    if (list == null)
                    {
                        Debug.LogError($"[TurnKit] Relay '{relay.slug}' contains a null list entry.");
                        return false;
                    }

                    if (!IsValidEnumSafeSlug(list.name, out string error))
                    {
                        Debug.LogError($"[TurnKit] Invalid list name '{list.name}' in relay '{relay.slug}'. {error}");
                        return false;
                    }

                    if (!listNames.Add(list.name))
                    {
                        Debug.LogError($"[TurnKit] Duplicate list name '{list.name}' in relay '{relay.slug}'.");
                        return false;
                    }
                }
            }

            return true;
        }

        private static bool IsValidEnumSafeSlug(string value, out string error)
        {
            error = null;

            if (string.IsNullOrWhiteSpace(value))
            {
                error = "List name cannot be empty.";
                return false;
            }

            if (value.Length > 64)
            {
                error = "List name must be 64 characters or less.";
                return false;
            }

            if (!Regex.IsMatch(value, "^[a-z][a-z0-9_]*$"))
            {
                error = "Use lowercase letters, numbers, and underscores only, and start with a letter.";
                return false;
            }

            if (value.Contains("__"))
            {
                error = "Double underscores are not allowed.";
                return false;
            }

            if (ReservedListNames.Contains(value))
            {
                error = "This name is reserved in C# and cannot be used.";
                return false;
            }

            return true;
        }

        private static string ToConfigClassName(string slug)
        {
            if (string.IsNullOrWhiteSpace(slug))
                return "UnnamedConfig";

            string flattened = Regex.Replace(slug, @"[^a-zA-Z0-9]+", " ");
            var parts = flattened.Split(new[] { ' ' }, System.StringSplitOptions.RemoveEmptyEntries);

            var sb = new StringBuilder();
            foreach (var part in parts)
            {
                if (part.Length == 0)
                    continue;

                sb.Append(char.ToUpperInvariant(part[0]));
                if (part.Length > 1)
                    sb.Append(part.Substring(1).ToLowerInvariant());
            }

            if (sb.Length == 0)
                sb.Append("Unnamed");

            if (char.IsDigit(sb[0]))
                sb.Insert(0, "_");

            sb.Append("Config");
            return sb.ToString();
        }
    }
}
