using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEngine;

namespace TurnKit.Editor
{
    public static class EnumGenerator
    {
        private const string GeneratedFileName = "RelayListNames.cs";
        private const string PlayerStoreGeneratedFileName = "PlayerStoreDefs.cs";

        public static void Generate(TurnKitConfig config)
        {
            if (config == null)
            {
                Debug.LogWarning("[TurnKit] No config to generate from");
                return;
            }

            if (!Validate(config))
            {
                return;
            }

            WriteGeneratedFile(ResolveRelayOutputPath(), BuildRelayGeneratedContent(config));
            WriteGeneratedFile(ResolvePlayerStoreOutputPath(), BuildPlayerStoreGeneratedContent(config));
            AssetDatabase.Refresh();
            Debug.Log("[TurnKit] Generated relay and player store enums");
        }

        public static bool HasChanges(TurnKitConfig config)
        {
            if (config == null)
            {
                return false;
            }

            return HasFileChanged(ResolveRelayOutputPath(), BuildRelayGeneratedContent(config)) ||
                   HasFileChanged(ResolvePlayerStoreOutputPath(), BuildPlayerStoreGeneratedContent(config));
        }

        private static string ResolveRelayOutputPath()
        {
            string turnKitRoot = ResolveTurnKitRoot();
            string[] existingGeneratedFiles = AssetDatabase.FindAssets($"{Path.GetFileNameWithoutExtension(GeneratedFileName)} t:MonoScript")
                .Select(AssetDatabase.GUIDToAssetPath)
                .Where(path =>
                    path.EndsWith($"/{GeneratedFileName}") &&
                    path.StartsWith(turnKitRoot + "/"))
                .ToArray();

            if (existingGeneratedFiles.Length > 0)
            {
                return existingGeneratedFiles[0];
            }

            return $"{turnKitRoot}/Runtime/Generated/{GeneratedFileName}";
        }

        private static string ResolvePlayerStoreOutputPath()
        {
            string turnKitRoot = ResolveTurnKitRoot();
            string[] existingGeneratedFiles = AssetDatabase.FindAssets($"{Path.GetFileNameWithoutExtension(PlayerStoreGeneratedFileName)} t:MonoScript")
                .Select(AssetDatabase.GUIDToAssetPath)
                .Where(path =>
                    path.EndsWith($"/{PlayerStoreGeneratedFileName}") &&
                    path.StartsWith(turnKitRoot + "/"))
                .ToArray();

            if (existingGeneratedFiles.Length > 0)
            {
                return existingGeneratedFiles[0];
            }

            return $"{turnKitRoot}/Runtime/Generated/{PlayerStoreGeneratedFileName}";
        }

        private static string ResolveTurnKitRoot()
        {
            string generatorPath = AssetDatabase.FindAssets("EnumGenerator t:MonoScript")
                .Select(AssetDatabase.GUIDToAssetPath)
                .FirstOrDefault(path => path.EndsWith("/Editor/Core/EnumGenerator.cs"));

            if (string.IsNullOrEmpty(generatorPath))
            {
                return "Assets/TurnKit";
            }

            string coreDirectory = Path.GetDirectoryName(generatorPath)?.Replace('\\', '/');
            string editorDirectory = Path.GetDirectoryName(coreDirectory)?.Replace('\\', '/');
            string turnKitRoot = Path.GetDirectoryName(editorDirectory)?.Replace('\\', '/');
            return string.IsNullOrEmpty(turnKitRoot) ? "Assets/TurnKit" : turnKitRoot;
        }

        private static string BuildRelayGeneratedContent(TurnKitConfig config)
        {
            var sb = new StringBuilder();
            var generatedClassNames = new List<(string Slug, string ClassName)>();

            sb.AppendLine("// This file is auto-generated by TurnKit. Do not edit manually.");
            sb.AppendLine("// Generated from relay configurations in TurnKitConfig");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine();
            sb.AppendLine("namespace TurnKit");
            sb.AppendLine("{");

            foreach (var relay in config.relayConfigs)
            {
                if (relay == null)
                {
                    continue;
                }

                string className = ToConfigClassName(relay.slug);
                generatedClassNames.Add((relay.slug, className));

                sb.AppendLine($"    public static class {className}");
                sb.AppendLine("    {");
                sb.AppendLine($"        public const string Slug = \"{relay.slug}\";");
                sb.AppendLine();

                string listMembers = relay.lists != null && relay.lists.Count > 0
                    ? string.Join(", ", relay.lists.Select(l => l.name))
                    : "__none";
                sb.AppendLine($"        public enum List {{ {listMembers} }}");

                var uniqueTags = relay.lists?
                    .Select(l => l.tag)
                    .Where(t => !string.IsNullOrEmpty(t))
                    .Distinct()
                    .ToList() ?? new List<string>();
                sb.AppendLine($"        public enum Tag {{ {(uniqueTags.Count > 0 ? string.Join(", ", uniqueTags) : "__none")} }}");
                sb.AppendLine();

                sb.AppendLine("        internal static readonly Dictionary<List, TurnKitConfig.RelayListConfig> ListMetadata = new()");
                sb.AppendLine("        {");
                if (relay.lists != null)
                {
                    foreach (var list in relay.lists)
                    {
                        string ownerSlots = string.Join(", ", list.ownerSlots.Select(s => $"TurnKitConfig.PlayerSlot.{s}"));
                        string visibleSlots = string.Join(", ", list.visibleToSlots.Select(s => $"TurnKitConfig.PlayerSlot.{s}"));
                        string tagValue = string.IsNullOrEmpty(list.tag) ? "string.Empty" : $"nameof(Tag.{list.tag})";

                        sb.AppendLine($"            {{ List.{list.name}, new TurnKitConfig.RelayListConfig {{");
                        sb.AppendLine($"                name = \"{list.name}\",");
                        sb.AppendLine($"                tag = {tagValue},");
                        sb.AppendLine($"                ownerSlots = new List<TurnKitConfig.PlayerSlot> {{ {ownerSlots} }},");
                        sb.AppendLine($"                visibleToSlots = new List<TurnKitConfig.PlayerSlot> {{ {visibleSlots} }}");
                        sb.AppendLine("            } },");
                    }
                }
                sb.AppendLine("        };");
                sb.AppendLine();

                sb.AppendLine("        internal static readonly Dictionary<string, TrackedStatMetadata> StatMetadata = new()");
                sb.AppendLine("        {");
                if (relay.trackedStats != null)
                {
                    foreach (var stat in relay.trackedStats)
                    {
                        string listInitializers = string.Join(", ", (stat.initialList ?? new List<string>())
                            .Select(item => ToCSharpStringLiteral(item ?? string.Empty)));
                        string initialValue = stat.dataType switch
                        {
                            TurnKitConfig.TrackedStatDataType.DOUBLE => $"InitialDouble = {stat.initialDouble.ToString(System.Globalization.CultureInfo.InvariantCulture)}d",
                            TurnKitConfig.TrackedStatDataType.STRING => $"InitialString = {ToCSharpStringLiteral(stat.initialString ?? string.Empty)}",
                            TurnKitConfig.TrackedStatDataType.LIST_STRING => $"InitialList = new List<string> {{ {listInitializers} }}",
                            _ => null
                        };

                        sb.AppendLine($"            {{ \"{stat.name}\", new TrackedStatMetadata {{ Name = \"{stat.name}\", DataType = TurnKitConfig.TrackedStatDataType.{stat.dataType}, Scope = TurnKitConfig.TrackedStatScope.{stat.scope}, {initialValue} }} }},");
                    }
                }
                sb.AppendLine("        };");

                if (relay.trackedStats != null && relay.trackedStats.Count > 0)
                {
                    sb.AppendLine();
                    sb.AppendLine("        public static class Stats");
                    sb.AppendLine("        {");
                    foreach (var stat in relay.trackedStats)
                    {
                        string builderType = stat.dataType switch
                        {
                            TurnKitConfig.TrackedStatDataType.DOUBLE => "DoubleStatBuilder",
                            TurnKitConfig.TrackedStatDataType.STRING => "StringStatBuilder",
                            TurnKitConfig.TrackedStatDataType.LIST_STRING => "ListStringStatBuilder",
                            _ => null
                        };

                        string valueType = stat.dataType switch
                        {
                            TurnKitConfig.TrackedStatDataType.DOUBLE => "double",
                            TurnKitConfig.TrackedStatDataType.STRING => "string",
                            TurnKitConfig.TrackedStatDataType.LIST_STRING => "IReadOnlyList<string>",
                            _ => null
                        };

                        if (string.IsNullOrEmpty(builderType) || string.IsNullOrEmpty(valueType))
                        {
                            continue;
                        }

                        string memberName = ToEnumMemberName(stat.name);
                        string tokenType = stat.scope == TurnKitConfig.TrackedStatScope.PER_PLAYER
                            ? $"PlayerStatToken<{valueType}, {builderType}>"
                            : $"MatchStatToken<{valueType}, {builderType}>";
                        sb.AppendLine($"            public static readonly {tokenType} {memberName} = new {tokenType}(StatMetadata[\"{stat.name}\"]);");
                    }
                    sb.AppendLine("        }");
                }
                sb.AppendLine("    }");
                sb.AppendLine();
            }

            sb.AppendLine("    internal static class Registry");
            sb.AppendLine("    {");
            sb.AppendLine("        public static readonly Dictionary<string, Action> Initializers = new()");
            sb.AppendLine("        {");
            for (int i = 0; i < generatedClassNames.Count; i++)
            {
                var item = generatedClassNames[i];
                string comma = i < generatedClassNames.Count - 1 ? "," : "";
                sb.AppendLine($"            {{ \"{item.Slug}\", () => Relay.Instance.InitializeFromMetadata({item.ClassName}.ListMetadata, {item.ClassName}.StatMetadata) }}{comma}");
            }
            sb.AppendLine("        };");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static string BuildPlayerStoreGeneratedContent(TurnKitConfig config)
        {
            var sb = new StringBuilder();
            var defs = config.playerStoreDefs ?? new List<TurnKitConfig.PlayerStoreDefConfig>();
            var usedMembers = new HashSet<string>();

            sb.AppendLine("// This file is auto-generated by TurnKit. Do not edit manually.");
            sb.AppendLine("// Generated from player store definitions in TurnKitConfig");
            sb.AppendLine();
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine();
            sb.AppendLine("namespace TurnKit");
            sb.AppendLine("{");
            sb.AppendLine("    public static class PlayerStoreDefs");
            sb.AppendLine("    {");

            foreach (var def in defs)
            {
                if (def == null || string.IsNullOrWhiteSpace(def.storeKey))
                {
                    continue;
                }

                string memberName = ToEnumMemberName(def.storeKey);
                if (!usedMembers.Add(memberName))
                {
                    Debug.LogWarning($"[TurnKit] Skipping duplicate player store key member collision: '{def.storeKey}' -> '{memberName}'.");
                    continue;
                }

                string valueType = def.valueType switch
                {
                    TurnKitConfig.PlayerStoreValueType.STRING => "string",
                    TurnKitConfig.PlayerStoreValueType.NUMBER => "decimal",
                    TurnKitConfig.PlayerStoreValueType.STRING_LIST => "IReadOnlyList<string>",
                    _ => "object"
                };

                sb.AppendLine($"        public static readonly PlayerStoreToken<{valueType}> {memberName} = new(\"{def.storeKey}\", TurnKitConfig.PlayerStoreValueType.{def.valueType}, {def.clientWritable.ToString().ToLowerInvariant()}, {def.clientReadable.ToString().ToLowerInvariant()});");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static void WriteGeneratedFile(string outputPath, string content)
        {
            string directory = Path.GetDirectoryName(outputPath);
            if (!Directory.Exists(directory))
            {
                Directory.CreateDirectory(directory);
            }

            File.WriteAllText(outputPath, content);
        }

        private static bool HasFileChanged(string path, string generated)
        {
            if (!File.Exists(path))
            {
                return true;
            }

            string existing = File.ReadAllText(path);
            return existing != generated;
        }

        internal static bool Validate(TurnKitConfig config)
        {
            if (TurnKitConfigValidator.TryValidateConfig(config, out var errors))
            {
                return true;
            }

            TurnKitConfigValidator.LogErrors(errors);
            return false;
        }

        internal static string ToConfigClassName(string slug)
        {
            if (string.IsNullOrWhiteSpace(slug))
            {
                return "UnnamedConfig";
            }

            string flattened = Regex.Replace(slug, @"[^a-zA-Z0-9]+", " ");
            var parts = flattened.Split(new[] { ' ' }, System.StringSplitOptions.RemoveEmptyEntries);

            var sb = new StringBuilder();
            foreach (var part in parts)
            {
                if (part.Length == 0)
                {
                    continue;
                }

                sb.Append(char.ToUpperInvariant(part[0]));
                if (part.Length > 1)
                {
                    sb.Append(part.Substring(1).ToLowerInvariant());
                }
            }

            if (sb.Length == 0)
            {
                sb.Append("Unnamed");
            }

            if (char.IsDigit(sb[0]))
            {
                sb.Insert(0, "_");
            }

            sb.Append("Config");
            return sb.ToString();
        }

        internal static string ToEnumMemberName(string value)
        {
            if (string.IsNullOrWhiteSpace(value))
            {
                return "Unnamed";
            }

            var parts = value.Split(new[] { '_' }, System.StringSplitOptions.RemoveEmptyEntries);
            var sb = new StringBuilder();
            foreach (var part in parts)
            {
                if (part.Length == 0)
                {
                    continue;
                }

                sb.Append(char.ToUpperInvariant(part[0]));
                if (part.Length > 1)
                {
                    sb.Append(part.Substring(1));
                }
            }

            if (sb.Length == 0)
            {
                sb.Append("Unnamed");
            }

            if (char.IsDigit(sb[0]))
            {
                sb.Insert(0, "_");
            }

            return sb.ToString();
        }

        private static string ToCSharpStringLiteral(string value)
        {
            if (value == null)
            {
                return "null";
            }

            string escaped = value
                .Replace("\\", "\\\\")
                .Replace("\"", "\\\"");
            return "\"" + escaped + "\"";
        }
    }
}
